#some of the most ubiquitous packages
#together with dependencies, installs most of
#packages needed in my codes
install.packages("tidyverse")
install.packages("caret")
install.packages("keras")
install.packages("e1071")
install.packages("doParallel")
install.packages("xtable")
install.packages("AppliedPredictiveModeling")
install.packages("mlbench")
install.packages("fastICA")
install.packages("randomForest")
install.packages("gbm")
install.packages("gam")
install.packages("Hmisc")
install.packages("pROC")
install.packages("exiftoolr")
install.packages("devtools")
install.packages("roxygen2")
install.packages("testthat")
install.packages("knitr")
install.packages("RSQLite")
install.packages("nnet")
install.packages("tm")
install.packages("markdown")
install.packages("magick")
install.packages("palmerpenguins")


# load to check
library("tidyverse")
library("caret")
library("keras")
library("e1071")
library("doParallel")
library("xtable")
library("AppliedPredictiveModeling")
library("mlbench")
library("fastICA")
library("randomForest")
library("gbm")
library("gam")
library("Hmisc")
library("pROC")
library("exiftoolr")
library("devtools")
library("roxygen2")
library("testthat")
library("knitr")
library("RSQLite")
library("nnet")
library("tm")
library("markdown")
library("magick")
library("palmerpenguins")

